# Generated by Django 5.0.4 on 2024-04-06 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_name', models.CharField(max_length=500)),
                ('stu_address', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name_plural': 'Student',
                'db_table': 'Student',
            },
        ),
    ]
